package rdd

type TableSchema struct {
	Name        string
	Fields      map[string]FieldSchema
	ForeignKeys []ForeignKeySchema
}

type FieldSchema struct {
	Name          string
	PrimaryKey    bool
	UniqueKey     bool
	AutoGenerated bool
	Nullable      bool
	Default       string
	FieldType     string
}

type ForeignKeySchema struct {
	fields    []string
	reference string
}
