package schema

type Table struct {
	Name        string
	Fields      map[string]Field
	ForeignKeys []ForeignKey
}

type Field struct {
	Name          string
	PrimaryKey    bool
	UniqueKey     bool
	AutoGenerated bool
	Nullable      bool
	Default       string
	FieldType     string
}

type ForeignKey struct {
	Fields    []string
	Reference string
}
